//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_FinalProject_HL_SZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int book_id { get; set; }
        public string title { get; set; }
        public string language { get; set; }
        public Nullable<bool> isBorrowed { get; set; }
        public int category_id { get; set; }
        public int author_id { get; set; }
        public System.DateTime published_date { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
    }
}
